### ISSUE TITLE
Unhandled Exception Issue

### ISSUE THREAD

**Issue by AutoCarrot** [PhoenixARC/-PCK-Studio#38]
Adding or replacing a file in a .pck file gives you an Unhandled Exception error.

Not sure if this helps or not, but here's the exception text in the Details section:

** Exception Text **
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at PckStudio.Extensions.TreeViewExtensions.FindPath(TreeView treeView, String path)
   at PckStudio.MainForm.BuildMainTreeView()
   at PckStudio.MainForm.replaceToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![Screenshot 2024-06-27 162004.png](https://github.com/PhoenixARC/-PCK-Studio/assets/133253797/1c9a2b72-288e-492b-9b80-66ec292c9035)

**Comment by NessieHax** [comment]
Will look into it

**Comment by NessieHax** [comment]
Fix in 5a086fd
